### PR TITLE
2023 Data Update

### PR DESCRIPTION
**Pull request by giacomoorsi**
I have downloaded and re-done all computations with all data available for 2023. 

This also comes with some new things: 
- Trains IDs are not (randomly) monotonically increasing assigned anymore, but they're a concatenation of `"train_class", "train_number", "train_departure_stop_name", "train_arrival_stop_name"`. The previous approach was not ideal because every time we were recomputing the statistics, the IDs were changing, so we also had to re-run the script that matches each train with its journey on the map. 
- Need for a new scale
- New outlier detection (removing statistics for a stop or a train if it did not occur for at least 12 distinct days) [there was an observation of an EuroCity in Sicily 🤣]

#  New color scale
It seems that by using data of the entire year, average delays are way higher (could be that we had previously picked a particularly good period during winter, or in general that the mean is very sensitive to outliers). 
Therefore, to show meaningful (and beautiful) charts there might be the need to use a new color scale. 

Previous regional differences map (data Dec 2022 - Feb 2023) (InterCity trains)
image

Regional differences map with 2023 data, without changing scale (InterCity trains)
image

Homepage stations map (data Dec 2022 - Feb 2023)
image

Homepage stations map with 2023 data, without changing scale
image

## Proposal
My proposal is to change the scale from this one: 
image

to this one: 
image

### How will the visualizations look like
Homepage
image

Regional differences of InterCity trains
image

# Data quality checks
Before merging, I think there are a few investigations to be carried out. 
- The worst station is Osteglia with a 94' average delay? That sounds impossible

### CODE REVIEW

**Review by frasalvi — COMMENTED** [review]
Great round of updates, thanks for the push!! 💪
The new color scale looks good to me. 

I am a bit perplexed by some new results and statistics. In addition to Ostiglia having a 94' average delay, which you already pointed out, I also see as the worst train the IC1963 with 121', also not looking right. Initially, I thought that it was an outlier problem, i.e. the train only ran once and was particularly bad, but looking at the [interpolated path](https://deploy-preview-25--openritardi.netlify.app/trains.html?train_id=IC1963MILANO%20CENTRALEVILLA%20SAN%20GIOVANNI), which is also clearly wrong, I have the suspect that the scheduled path changed throughout the year. This seems to be confirmed by some [news articles](https://www.ferrovie.info/index.php/it/66-archivio-news-2022/24664-ferrovie-le-novita-e-le-variazioni-di-percorso-degli-intercity-notte-di-trenitalia).

I think that we need at some point to improve the robustness of our system for connecting paths and for detecting outliers. Concerning the latter, could you maybe quickly summarize or point out to me the part of the code that manages outliers, both in terms of stations/trains/stops? (yes, I could check the notebooks myself, but I figured since you are our master data wrangler it would be easier for you to find that :P)

**Comment by frasalvi** [comment]
A potential bug with the new color scale is that Ostiglia is shown as black. Could it be that somehow values that are too much outside of the specified range aren't converted correctly? If that's the case, this was almost surely a problem for the old scale too, that we just hadn't spotted.

**Comment by giacomoorsi** [comment]
> I think that we need at some point to improve the robustness of our system for connecting paths and for detecting outliers. Concerning the latter, could you maybe quickly summarize or point out to me the part of the code that manages outliers, both in terms of stations/trains/stops? (yes, I could check the notebooks myself, but I figured since you are our master data wrangler it would be easier for you to find that :P)

Correct. Currently the schedule is inferred from the delays data. Ideally, it should take the "most common schedule" but unfortunately it's hard to extract it and this leads to issues. There's also the issue with multi-day InterCity trains which cause issues because stops are sorted based on the arrival time, regardless of the day. In general, the schedule extraction should be improved. 

Outlier detection is one in the `data_generation.ipynb` notebook, if you look for the keyword `THRESHOLD` this appears only when there's an outlier removal. 

To quickly sum up the outlier removal in place: 
- removing all delays outside this range: [-100, 300]
- removing all stations that didn't appear on at least 12 different days
- removing all trains that didn't appear on at least 48 different days (4 times a month)

**Comment by giacomoorsi** [comment]
Regarding Ofelia mentioned above... the issue arises from the fact that in this station, the effective arrival time of the train is never recorded (always n.d.) apart from a single observation, with 90' delay. Therefore, the stop was not removed by the outlier detection (as there's many trains stopping there), but the average delay is computed on a single valid delay value. I'm working on a solution

**Comment by giacomoorsi** [comment]
Update: 
Now I am removing all "NA" delays when doing computations, and therefore I am able to identify as outliers those stops which have many many observations but only a few with the actual detected delays, and I remove them. 

image

However I'm now having this phenomenon. In Liguria, apparently, the real delay is detected only in certain stops, so now it looks like some stops have way fewer trains than others, while it's not the case in reality
I will investigate further but in the meantime I've pushed the changes, and the updated datasets. 

Actually, how should we handle that? For instance, the station of "Celle" has in reality the same amount of trains as "Albisola". However, for some reasons, most of the times the real delay is not recorded for "Celle", and the few times it is recorded, it is for very delayed trains. Instead, the real delay distribution is probably the same for the two stops, and also the station dot should have the same size. 
image

**Idea** (requires some website logic changes and data process changes, though): the size of the dot and the popup "number of trains" should reflect the number of observations that we have for a stop, regardless of how many recorded delays we have. Then, the dot is shown grey if we don't have enough recorded delays (e.g. < 20% of number of trains), else it's colored based on the delay. What do you think? @roberto-ceraolo @frasalvi

**Comment by giacomoorsi** [comment]
> ### ❌ Deploy Preview for _openritardi_ failed.
> Name	Link
> 🔨 Latest commit	[f5a62d3](https://github.com/giacomoorsi/OpenRitardi/commit/f5a62d321bd41a8ec5636bab8a302a0c9f9bce99)
> 🔍 Latest deploy log	https://app.netlify.com/sites/openritardi/deploys/65bac7fd1c26e4000871b9dc

I have added `git lfs` for the zip files, in order to keep the commit history lighter but it seems this make netlify fail, I will try to look for a fix. 



Update: 
> ### ✅ Deploy Preview for _openritardi_ ready!
Fixed, by changing some settings in Netlify to allow downloading git lfs files

**Comment by frasalvi** [comment]
+1 for the idea of computing the dot size respectively of delays.

**Comment by giacomoorsi** [comment]
Opening pull request. I think we can merge it regardless of all those little data issues, and just keep the PR open for a roadmap of activities

**Review by roberto-ceraolo — APPROVED** [review]
all good.

**Pull request merged**
